### ISSUE TITLE
Centralize Forklift/MTV PR-BZ map

### ISSUE THREAD

**Issue by rayfordj** [konveyor/bz-github-action#10]
Similar to what we did for Crane/MTC on https://github.com/konveyor/bz-github-action/issues/2

Repos:

- forklift-controller
- forklift-operator
- forklift-ui
- forklift-validation
- forklift-must-gather

**Comment by rayfordj** [comment]
```
secrets.MTV_PR_BZ_MAP
```

```
'release-v2.0.0:2.0.0,release-v2.1.0:2.1.0,main:2.1.0'
```

**Comment by rayfordj** [comment]
Direct link to [secrets.MTV_PR_BZ_MAP](https://github.com/organizations/konveyor/settings/secrets/actions/MTV_PR_BZ_MAP) for reference.

**Comment by ghost** [comment]
At this stage, I guess that `main` branch maps to `2.2.0`, instead of `2.1.0`. Do we simply need to set a new value for the secret?

**Comment by rayfordj** [comment]
> At this stage, I guess that `main` branch maps to `2.2.0`, instead of `2.1.0`. Do we simply need to set a new value for the secret?

@fdupont-redhat , this was a discussion with @fbladilo and he elected to keep `2.1.0` when I asked ( [pull/727#discussion_r677822882](https://github.com/konveyor/forklift-ui/pull/727#discussion_r677822882) ).  If that's not the case, yes, update the quoted mapping string in the secret and roll with it.  :sunglasses:

**Comment by rayfordj** [comment]
@fdupont-redhat / @fbladilo , another discussion item for consideration:  a place for the most recent plain-text mapping string to reside for easy review.  I've no strong opinions on _where_ -- initial thoughts are in a "docs" file under forklift-operator so it resides under "Forklift" purview.  The intention is to have a single point of authority for what should be the contents of the secret that anybody with the privilege to update the secret may use to set a 'last known good' map if there's ever a concern.

The workflow might be something like:

- Submit PR with updated map string
- Upon PR 'ack', update secret.MTV_PR_BZ_MAP
- Merge PR

I leave it to you to decide the best course because you'll be maintaining the map.
